<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { color: #111827; font-family: DejaVu Sans, sans-serif; font-size: 11px; line-height: 1.35; }
        .header { text-align: center; }
        .logo { height: 70px; margin-bottom: 6px; }
        h1 { font-size: 15px; margin: 4px 0 2px; text-transform: uppercase; }
        h2 { border-bottom: 1px solid #111827; font-size: 12px; margin: 16px 0 8px; padding-bottom: 3px; text-transform: uppercase; }
        table { border-collapse: collapse; width: 100%; }
        td, th { border: 1px solid #111827; padding: 6px; vertical-align: top; }
        th { background: #e7f3ea; font-weight: bold; text-align: left; }
        .no-border td { border: 0; padding: 3px 0; }
        .muted { color: #4b5563; font-size: 10px; }
        .signatures td { height: 58px; }
        .checkbox { display: inline-block; height: 10px; margin-right: 5px; width: 10px; border: 1px solid #111827; }
    </style>
</head>
<body>
@php
    $form = $form ?? [];
    $value = fn (string $key, string $fallback = '-') => $form[$key] ?? $fallback;
@endphp
<div class="header">
    <img class="logo" src="{{ public_path('images/kfs-logo.png') }}" alt="Kenya Forest Service logo">
    <h1>Kenya Forest Service</h1>
    <div><strong>Application for Leave / Off Duty</strong></div>
    <div class="muted">Generated by KFS Smart HRMS on {{ now()->format('d/m/Y H:i') }}</div>
</div>

<h2>Employee Details</h2>
<table>
    <tr>
        <th style="width: 22%;">Name</th><td>{{ $value('employee_name') }}</td>
        <th style="width: 20%;">Staff No.</th><td>{{ $value('employee_number') }}</td>
    </tr>
    <tr>
        <th>Station / Conservancy</th><td>{{ $value('station', 'Not captured') }}</td>
        <th>Department</th><td>{{ $value('department', 'Not captured') }}</td>
    </tr>
    <tr>
        <th>Designation</th><td>{{ $value('designation', 'Not captured') }}</td>
        <th>Terms of Service</th><td>{{ $value('terms') }}</td>
    </tr>
</table>

<h2>Leave Details</h2>
<table>
    <tr>
        <th style="width: 22%;">Type of Leave</th><td>{{ $value('leave_type', 'Leave') }}</td>
        <th style="width: 20%;">Days Applied</th><td>{{ $value('requested_days', '0.00') }}</td>
    </tr>
    <tr>
        <th>Start Date</th><td>{{ $value('start_date') }}</td>
        <th>End Date</th><td>{{ $value('end_date') }}</td>
    </tr>
    <tr>
        <th>Expected Resume Date</th><td>{{ $value('resume_date') }}</td>
        <th>Status</th><td>{{ $value('status') }}</td>
    </tr>
    <tr>
        <th>Reason / Remarks</th><td colspan="3">{{ $value('reason') }}</td>
    </tr>
</table>

<h2>Leave Type Checklist</h2>
<table>
    <tr>
        @foreach (['Annual Leave', 'Sick Leave', 'Maternity Leave', 'Paternity Leave'] as $type)
            <td><span class="checkbox">{{ $value('leave_type') === $type ? 'X' : '' }}</span>{{ $type }}</td>
        @endforeach
    </tr>
    <tr>
        @foreach (['Compassionate Leave', 'Study Leave', 'Special Leave', 'Off Day Request'] as $type)
            <td><span class="checkbox">{{ $value('leave_type') === $type ? 'X' : '' }}</span>{{ $type }}</td>
        @endforeach
    </tr>
</table>

<h2>Approval</h2>
<table>
    <tr>
        <th style="width: 25%;">Responsible Approver</th>
        <td>{{ $value('approver', 'HR Admin / HR Manager') }}</td>
        <th style="width: 18%;">Decision</th>
        <td>{{ $value('decision', 'Pending') }}</td>
    </tr>
    <tr>
        <th>Decision Date</th><td>{{ $value('decision_at') }}</td>
        <th>Remarks</th><td>{{ $value('approval_remarks') }}</td>
    </tr>
</table>

<h2>Declaration and Sign-Off</h2>
<table class="signatures">
    <tr>
        <th>Applicant Signature</th>
        <th>Supervisor / Station Head</th>
        <th>HR Admin / Manager</th>
    </tr>
    <tr>
        <td>Name: {{ $value('employee_name') }}<br>Date: ____________________</td>
        <td>Name: ____________________<br>Date: ____________________</td>
        <td>Name: {{ $value('approver', '____________________') }}<br>Date: {{ $value('decision_date', '____________________') }}</td>
    </tr>
</table>
</body>
</html>
